// <auto-generated />
using System;
using EventEase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventEase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611143812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventEase.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("EventId");

                    b.HasIndex("VenueId", "BookingDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_Booking_Venue_Date");

                    b.ToTable("Bookings", (string)null);

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            BookingDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4530),
                            EventId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            BookingId = 2,
                            BookingDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4532),
                            EventId = 2,
                            VenueId = 3
                        },
                        new
                        {
                            BookingId = 3,
                            BookingDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4534),
                            EventId = 3,
                            VenueId = 2
                        },
                        new
                        {
                            BookingId = 4,
                            BookingDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4535),
                            EventId = 4,
                            VenueId = 4
                        });
                });

            modelBuilder.Entity("EventEase.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4500),
                            Description = "Technology innovation showcase with keynote speakers and workshops",
                            EventDate = new DateTime(2026, 6, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Annual Tech Conference",
                            EventTypeId = 1,
                            ImageUrl = "https://placehold.co/600x400/8b5cf6/white?text=Tech+Conference",
                            VenueId = 1
                        },
                        new
                        {
                            EventId = 2,
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4503),
                            Description = "Smith-Johnson wedding reception with dinner and dancing",
                            EventDate = new DateTime(2026, 7, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Wedding Reception",
                            EventTypeId = 2,
                            ImageUrl = "https://placehold.co/600x400/ec4899/white?text=Wedding+Reception",
                            VenueId = 3
                        },
                        new
                        {
                            EventId = 3,
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4505),
                            Description = "New product reveal for the latest tech innovation",
                            EventDate = new DateTime(2026, 5, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Product Launch",
                            EventTypeId = 1,
                            ImageUrl = "https://placehold.co/600x400/14b8a6/white?text=Product+Launch",
                            VenueId = 2
                        },
                        new
                        {
                            EventId = 4,
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4507),
                            Description = "Quarterly review and strategic planning session",
                            EventDate = new DateTime(2026, 5, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Board Meeting",
                            EventTypeId = 4,
                            ImageUrl = "https://placehold.co/600x400/f97316/white?text=Board+Meeting",
                            VenueId = 4
                        });
                });

            modelBuilder.Entity("EventEase.Models.EventType", b =>
                {
                    b.Property<int>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventTypeId"));

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EventTypeId");

                    b.ToTable("EventTypes", (string)null);

                    b.HasData(
                        new
                        {
                            EventTypeId = 1,
                            ColorClass = "primary",
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4355),
                            Description = "Professional conferences and seminars",
                            IconClass = "bi-people-fill",
                            IsActive = true,
                            TypeName = "Conference"
                        },
                        new
                        {
                            EventTypeId = 2,
                            ColorClass = "danger",
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4357),
                            Description = "Wedding ceremonies and receptions",
                            IconClass = "bi-heart-fill",
                            IsActive = true,
                            TypeName = "Wedding"
                        },
                        new
                        {
                            EventTypeId = 3,
                            ColorClass = "success",
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4359),
                            Description = "Live music and performances",
                            IconClass = "bi-music-note-beamed",
                            IsActive = true,
                            TypeName = "Concert"
                        },
                        new
                        {
                            EventTypeId = 4,
                            ColorClass = "info",
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4361),
                            Description = "Business meetings and corporate events",
                            IconClass = "bi-briefcase-fill",
                            IsActive = true,
                            TypeName = "Corporate"
                        },
                        new
                        {
                            EventTypeId = 5,
                            ColorClass = "warning",
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4362),
                            Description = "Birthdays, anniversaries, private celebrations",
                            IconClass = "bi-gift-fill",
                            IsActive = true,
                            TypeName = "Private Party"
                        },
                        new
                        {
                            EventTypeId = 6,
                            ColorClass = "secondary",
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4364),
                            Description = "Educational workshops and training",
                            IconClass = "bi-mortarboard-fill",
                            IsActive = true,
                            TypeName = "Workshop"
                        });
                });

            modelBuilder.Entity("EventEase.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VenueId");

                    b.ToTable("Venues", (string)null);

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Capacity = 500,
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4469),
                            ImageUrl = "https://placehold.co/600x400/3b82f6/white?text=Grand+Ballroom",
                            IsAvailable = true,
                            Location = "123 Main St, City Center",
                            VenueName = "Grand Ballroom"
                        },
                        new
                        {
                            VenueId = 2,
                            Capacity = 200,
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4471),
                            ImageUrl = "https://placehold.co/600x400/10b981/white?text=Conference+Hall+A",
                            IsAvailable = true,
                            Location = "45 Business Park",
                            VenueName = "Conference Hall A"
                        },
                        new
                        {
                            VenueId = 3,
                            Capacity = 150,
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4472),
                            ImageUrl = "https://placehold.co/600x400/f59e0b/white?text=Garden+Pavilion",
                            IsAvailable = true,
                            Location = "789 Park Avenue",
                            VenueName = "Garden Pavilion"
                        },
                        new
                        {
                            VenueId = 4,
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 6, 11, 16, 38, 11, 891, DateTimeKind.Local).AddTicks(4474),
                            ImageUrl = "https://placehold.co/600x400/ef4444/white?text=Executive+Boardroom",
                            IsAvailable = true,
                            Location = "45 Business Park",
                            VenueName = "Executive Boardroom"
                        });
                });

            modelBuilder.Entity("EventEase.Models.Booking", b =>
                {
                    b.HasOne("EventEase.Models.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventEase.Models.Venue", "Venue")
                        .WithMany("Bookings")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventEase.Models.Event", b =>
                {
                    b.HasOne("EventEase.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventEase.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EventType");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventEase.Models.Event", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EventEase.Models.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventEase.Models.Venue", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
